apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest  # Image that already includes curl
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do sleep 3600; done;"  # Keeps the container running
